---
# Role: nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Create vhost configuration
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.name }}"
  loop: "{{ sites }}"
  notify: reload nginx

- name: Enable vhost
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}"
    state: link
  loop: "{{ sites }}"
  notify: reload nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
