---
# Deploy user
deploy_user: deploy

# Sites configuration
sites:
  - name: busification
    domain: run-game.fun
    root: /var/www/busification-run
    api_port: 3000

# MySQL
mysql_root_password: "5t!D!7O4N8iV"
mysql_database: game
mysql_user: game_user
mysql_password: "&9ev.dr4RQ48"

# Admin
admin_password: "Aspirine1210"

# App
app_repo: https://github.com/foxcreator/run_game.git
app_branch: main

# Node.js
nodejs_version: "20"

# SSH
ssh_port: 22

# GitHub Runner

